/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../../core";

export const CreateApplicationUser: core.serialization.Schema<
    serializers.CreateApplicationUser.Raw,
    IntegralApi.CreateApplicationUser
> = core.serialization.object({
    applicationUserForeignId: core.serialization.string(),
    applicationTierId: core.serialization.string(),
});

export declare namespace CreateApplicationUser {
    interface Raw {
        applicationUserForeignId: string;
        applicationTierId: string;
    }
}
