/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../../core";

export const CreateApplicationUser: core.serialization.Schema<
    serializers.CreateApplicationUser.Raw,
    IntegralApi.CreateApplicationUser
> = core.serialization.object({
    userId: core.serialization.string(),
    tierId: core.serialization.string(),
    description: core.serialization.string().optional(),
});

export declare namespace CreateApplicationUser {
    interface Raw {
        userId: string;
        tierId: string;
        description?: string | null;
    }
}
