/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface ApiKey {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    apiKey: string;
    isPaused: boolean;
    isRevoked: boolean;
    isRotatedOff: boolean;
    numOfRequest: number;
    firstTimeRequest: string;
    applicationUser: IntegralApi.ApplicationUser;
}
