/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApiKey {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    apiKey: string;
    name?: string;
    expiresAt: string;
    description?: string;
    isPaused: boolean;
    isRevoked: boolean;
    lastUsed?: string;
}
