/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApplicationBaseUrl {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    url: string;
}
