/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface Application {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    name: string;
    description: string;
    publicId: string;
    organization: IntegralApi.Organization;
    baseUrl: IntegralApi.ApplicationBaseUrl;
    ipRateLimit: number;
    amountPerInterval?: string;
    timeInterval: string;
}
