/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApplicationBaseUrlEndpoint {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    path: string;
    name: string;
    scopeKey: string;
    description: string;
    method: string;
    queryParams?: Record<string, unknown>;
    requestBody?: Record<string, unknown>;
    requestHeaders?: Record<string, unknown>;
    sandboxFieldLocation?: string;
    sandboxFieldName?: string;
}
