/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface ApplicationUserCreateResponse {
    applicationUser: IntegralApi.ApplicationUser;
    apiKey: IntegralApi.ApiKey;
}
