/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface ApplicationUser {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    applicationUserForeignId: string;
    metadata?: Record<string, unknown>;
    applicationRole: IntegralApi.ApplicationRole;
    application: IntegralApi.Application;
}
