/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApplicationRole {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    role: string;
    description?: string;
}
