/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../../core";

export const RevokeApiKeyRequest: core.serialization.Schema<
    serializers.RevokeApiKeyRequest.Raw,
    IntegralApi.RevokeApiKeyRequest
> = core.serialization.object({
    apiKey: core.serialization.string(),
});

export declare namespace RevokeApiKeyRequest {
    interface Raw {
        apiKey: string;
    }
}
