/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../../core";

export const UnpauseApiKeyRequest: core.serialization.Schema<
    serializers.UnpauseApiKeyRequest.Raw,
    IntegralApi.UnpauseApiKeyRequest
> = core.serialization.object({
    apiKey: core.serialization.string(),
});

export declare namespace UnpauseApiKeyRequest {
    interface Raw {
        apiKey: string;
    }
}
