/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApplicationParseResponse {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    name: string;
    description: string;
}
