/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IdempotencyKeyType {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    key: string;
    endpoint: Record<string, unknown>;
    expiresAt: string;
    apiKey: Record<string, unknown>;
    responseStatusCode?: number;
    responseBody: Record<string, unknown>;
}
