/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface PostProcessApiResponse {
    request: IntegralApi.RequestType;
    idempotencyKey: IntegralApi.IdempotencyKeyType;
}
