/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface PreProcessApiResponse {
    request: IntegralApi.RequestPreProcessResponse;
    statusCode: number;
    user: IntegralApi.UserParseResponse;
    application: IntegralApi.ApplicationParseResponse;
    returnBackToUser?: IntegralApi.ReturnBackToUserUnionType;
}
