/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface RequestPreProcessResponse {
    hasResponseContent: boolean;
    environment: string;
    id: string;
    version?: string;
    endpoint: IntegralApi.EndpointPreProcessType;
}
