/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RequestType {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    userApiKey: Record<string, unknown>;
    route: string;
    method: string;
    headers: Record<string, unknown>;
    traceback?: Record<string, unknown>;
    ip: string;
    isSandbox: boolean;
    metadata?: Record<string, unknown>;
    responseStatusCode: number;
    responseBody: Record<string, unknown>;
}
