/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ReturnBackToUserResponse {
    message: string;
    solution: string;
    apiKey: string;
    error: string;
    errorCode: string;
    displayMessage: string;
    documentationUrl?: string;
    causes?: string;
}
