/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ReturnBackToUserErrorResponse {
    message: string;
    solution: string;
    apiKey?: string;
    error?: boolean;
    errorCode: string;
    displayMessage: string;
    documentationUrl?: string;
    causes?: string;
}
