/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export type ReturnBackToUserUnionType = IntegralApi.ReturnBackToUserErrorResponse | Record<string, unknown>;
