/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserParseResponse {
    id: string;
    createdAt: string;
    firstName: string;
    lastName: string;
    email: string;
    isAdmin: boolean;
}
