/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserParseResponse {
    integralId: string;
    metadata?: Record<string, unknown>;
    userId: string;
    isAllowlistedOnEndpoint: boolean;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
    idempotencyKey?: string;
}
