/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ApplicationRole: core.serialization.ObjectSchema<
    serializers.ApplicationRole.Raw,
    IntegralApi.ApplicationRole
> = core.serialization.object({
    id: core.serialization.string(),
    createdAt: core.serialization.string(),
    updatedAt: core.serialization.string(),
    deletedAt: core.serialization.string().optional(),
    role: core.serialization.string(),
    description: core.serialization.string().optional(),
});

export declare namespace ApplicationRole {
    interface Raw {
        id: string;
        createdAt: string;
        updatedAt: string;
        deletedAt?: string | null;
        role: string;
        description?: string | null;
    }
}
