/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ApplicationVersion: core.serialization.ObjectSchema<
    serializers.ApplicationVersion.Raw,
    IntegralApi.ApplicationVersion
> = core.serialization.object({
    id: core.serialization.string(),
    createdAt: core.serialization.string(),
    updatedAt: core.serialization.string(),
    deletedAt: core.serialization.string().optional(),
    version: core.serialization.string(),
});

export declare namespace ApplicationVersion {
    interface Raw {
        id: string;
        createdAt: string;
        updatedAt: string;
        deletedAt?: string | null;
        version: string;
    }
}
