/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ApplicationUserCreateResponse: core.serialization.ObjectSchema<
    serializers.ApplicationUserCreateResponse.Raw,
    IntegralApi.ApplicationUserCreateResponse
> = core.serialization.object({
    applicationUser: core.serialization.lazyObject(async () => (await import("../../..")).ApplicationUser),
    productionApiKey: core.serialization.string(),
    sandboxApiKey: core.serialization.string(),
});

export declare namespace ApplicationUserCreateResponse {
    interface Raw {
        applicationUser: serializers.ApplicationUser.Raw;
        productionApiKey: string;
        sandboxApiKey: string;
    }
}
