/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ApplicationUserCreateResponse: core.serialization.ObjectSchema<
    serializers.ApplicationUserCreateResponse.Raw,
    IntegralApi.ApplicationUserCreateResponse
> = core.serialization.object({
    applicationUser: core.serialization.lazyObject(async () => (await import("../../..")).ApplicationUser),
    apiKey: core.serialization.lazyObject(async () => (await import("../../..")).ApiKey),
});

export declare namespace ApplicationUserCreateResponse {
    interface Raw {
        applicationUser: serializers.ApplicationUser.Raw;
        apiKey: serializers.ApiKey.Raw;
    }
}
