/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ApplicationBaseUrl: core.serialization.ObjectSchema<
    serializers.ApplicationBaseUrl.Raw,
    IntegralApi.ApplicationBaseUrl
> = core.serialization.object({
    id: core.serialization.string(),
    createdAt: core.serialization.string(),
    updatedAt: core.serialization.string(),
    deletedAt: core.serialization.string().optional(),
    url: core.serialization.string(),
});

export declare namespace ApplicationBaseUrl {
    interface Raw {
        id: string;
        createdAt: string;
        updatedAt: string;
        deletedAt?: string | null;
        url: string;
    }
}
