/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { IntegralApi } from "@fern-api/integral";
import * as core from "../../../core";

export const Request: core.schemas.Schema<
  serializers.apiKeys.generate.Request.Raw,
  IntegralApi.GenereateApiKeyRequest
> = core.schemas.object({
  applicationUserForeignId: core.schemas.string().optional(),
  description: core.schemas.string().optional(),
});

export declare namespace Request {
  interface Raw {
    applicationUserForeignId?: string | null;
    description?: string | null;
  }
}

export const Response: core.schemas.Schema<serializers.apiKeys.generate.Response.Raw, IntegralApi.ApiKey> =
  core.schemas.lazyObject(async () => (await import("../..")).ApiKey);

export declare namespace Response {
  type Raw = serializers.ApiKey.Raw;
}
