/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.apiKeys.revoke.Request.Raw, IntegralApi.RevokeApiKeyRequest> =
  core.schemas.object({
    apiKey: core.schemas.string(),
  });

export declare namespace Request {
  interface Raw {
    apiKey: string;
  }
}

export const Response: core.schemas.Schema<serializers.apiKeys.revoke.Response.Raw, IntegralApi.ApiKey> =
  core.schemas.lazyObject(async () => (await import("../..")).ApiKey);

export declare namespace Response {
  type Raw = serializers.ApiKey.Raw;
}
