/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class IntegralApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, IntegralApiTimeoutError.prototype);
    }
}
