/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApplicationUser {
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  applicationUserForeignId: string;
}
