/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GenerateApiKeyRequest {
    /**
     * This is a unique index on your database to find users.  This will allow us to know which API key associates to each user on your application's end.
     *
     */
    userId: string;
    /**
     * This is the name of the key that will be indexed and shown as a helpful human identifier for the key and it's relevant information (logs, events, and errors).
     *
     */
    name?: string;
    /**
     * Extra space for any additional metadata or information needed to be applied on a key.
     *
     */
    description?: string;
    /**
     * This value is a boolean to determine whether the key is for Sandbox use only or not. If it is for sandbox use, it will not be able to access real data and will only be able to work with templated data.
     *
     */
    isSandbox?: boolean;
}
