/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RetrieveSandboxApplicationUserApiKeys {
    /**
     * A range of number of keys wanted, min 1 and max 100. Default is 10.
     */
    limit?: number;
    /**
     * The ID of the previous page's last key (to retrieve the next set of rows)
     */
    after?: string;
}
