/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface RotateApiKeyRequest {
    /** This API key is generated by Integral and passed to the Application User. */
    apiKey: string;
    /** A human readable determined enum value of either `now`, `1h`, `24h`, `3d`, or `7d` of when we should revoke the given key */
    expiresIn: IntegralApi.RotateTimings;
}
