/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UnpauseApiKeyRequest {
    /** This API key is generated by Integral and passed to the Application User. */
    apiKey: string;
}
