/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface Log {
    id: string;
    createdAt: string;
    updatedAt: string;
    user: IntegralApi.ApplicationUser;
    application: IntegralApi.Application;
    userApiKey?: IntegralApi.ApiKey;
    route: string;
    method: string;
    body?: Record<string, unknown>;
    headers?: Record<string, unknown>;
    ip: string;
    isSandbox: boolean;
    metadata?: Record<string, unknown>;
    version?: string;
    endpoint?: IntegralApi.ApplicationBaseUrlEndpoint;
    responseStatusCode?: number;
    responseBody?: Record<string, unknown>;
}
