/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RotateTimings = "now" | "1h" | "24h" | "3d" | "7d";

export const RotateTimings = {
    Now: "now",
    OneHour: "1h",
    TwentyFourHours: "24h",
    ThreeDays: "3d",
    SevenDays: "7d",
} as const;
