/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ParseApiRequest {
    apiKey: string;
    ip: string;
    method: string;
    requestBody: Record<string, unknown>;
    headers: Record<string, unknown>;
    path: string;
    queryParams: Record<string, unknown>;
    metadata?: Record<string, unknown>;
}
