/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PostProcessApiRequest {
    /** This endpoint ID is taken from the pre-processing endpoint and passed in here. */
    endpointId: string;
    /** This request ID is taken from the pre-processing endpoint and passed in here. */
    requestId: string;
    /**
     * This is the status code your API will respond with for the given request. Must have a `2xx` status code.
     *
     */
    responseStatusCode: number;
    /**
     * This request body comes from expected return from your services. If the same idempotency key is sent, then we'll automatically return back this response body.
     *
     */
    requestBody: Record<string, unknown>;
    /**
     * This API key is the key passed in by your API's user. This is crucial for us to parse out your application's user. You can also find this apiKey returned by our pre-process endpoint.
     *
     */
    apiKey: string;
    /**
     * This key is a **user generated** unique identifier to map to a request. This allows requests to be safely retry requests without the risk of duplicating operations.
     * `GET`, `PUT`, and `DELETE` are generally safe to retry (according to standard REST practices). For `POST` and `PATCH` requests, is recommended to send and store the `idempotencyKey` in their system.
     * **It will be returned to you by our pre-process endpoint for consistency purposes.**
     *
     */
    idempotencyKey: string;
}
