/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GenereateApiKeyRequest {
  applicationUserForeignIdRequired?: string;
  description?: string;
  isSandbox?: boolean;
}
