/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../../core";

export const PostProcessApiRequest: core.serialization.Schema<
    serializers.PostProcessApiRequest.Raw,
    IntegralApi.PostProcessApiRequest
> = core.serialization.object({
    endpointId: core.serialization.string(),
    requestId: core.serialization.string(),
    responseStatusCode: core.serialization.number(),
    requestBody: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    apiKey: core.serialization.string(),
    idempotencyKey: core.serialization.string(),
});

export declare namespace PostProcessApiRequest {
    interface Raw {
        endpointId: string;
        requestId: string;
        responseStatusCode: number;
        requestBody: Record<string, unknown>;
        apiKey: string;
        idempotencyKey: string;
    }
}
