/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";

export interface ApplicationTier {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    role: string;
    description: string;
    application: IntegralApi.Application;
    applicationRateLimit: IntegralApi.ApplicationRateLimit;
}
