/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ApplicationRateLimit: core.serialization.ObjectSchema<
    serializers.ApplicationRateLimit.Raw,
    IntegralApi.ApplicationRateLimit
> = core.serialization.object({
    id: core.serialization.string(),
    createdAt: core.serialization.string(),
    updatedAt: core.serialization.string(),
    deletedAt: core.serialization.string().optional(),
    numOfRequests: core.serialization.number(),
    timeInterval: core.serialization.string(),
});

export declare namespace ApplicationRateLimit {
    interface Raw {
        id: string;
        createdAt: string;
        updatedAt: string;
        deletedAt?: string | null;
        numOfRequests: number;
        timeInterval: string;
    }
}
