/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as ApiKeysClient } from "./resources/apiKeys/client/Client";

export declare namespace IntegralApiClient {
  interface Options {
    environment?: environments.Environment | string;
    authentication?: core.Supplier<string>;
  }
}

export class IntegralApiClient {
  constructor(private readonly options: IntegralApiClient.Options) {}

  #apiKeys: ApiKeysClient | undefined;

  public get apiKeys(): ApiKeysClient {
    return (this.#apiKeys ??= new ApiKeysClient(this.options));
  }
}
