/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const IntegralApiEnvironment = {
    Production: "https://api.integralapi.co/public",
    Local: "http://localhost:3000/",
} as const;

export type IntegralApiEnvironment = typeof IntegralApiEnvironment.Production | typeof IntegralApiEnvironment.Local;
