/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ApiKeyParseResponse: core.serialization.ObjectSchema<
    serializers.ApiKeyParseResponse.Raw,
    IntegralApi.ApiKeyParseResponse
> = core.serialization.object({
    isAllowed: core.serialization.boolean(),
    environment: core.serialization.string().optional(),
});

export declare namespace ApiKeyParseResponse {
    interface Raw {
        isAllowed: boolean;
        environment?: string | null;
    }
}
