/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ApplicationParseResponse: core.serialization.ObjectSchema<
    serializers.ApplicationParseResponse.Raw,
    IntegralApi.ApplicationParseResponse
> = core.serialization.object({
    id: core.serialization.string(),
    createdAt: core.serialization.string(),
    updatedAt: core.serialization.string(),
    deletedAt: core.serialization.string().optional(),
    name: core.serialization.string(),
    description: core.serialization.string(),
});

export declare namespace ApplicationParseResponse {
    interface Raw {
        id: string;
        createdAt: string;
        updatedAt: string;
        deletedAt?: string | null;
        name: string;
        description: string;
    }
}
