/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const PostProcessApiResponse: core.serialization.ObjectSchema<
    serializers.PostProcessApiResponse.Raw,
    IntegralApi.PostProcessApiResponse
> = core.serialization.object({
    request: core.serialization.lazyObject(async () => (await import("../../..")).RequestType),
    idempotencyKey: core.serialization.lazyObject(async () => (await import("../../..")).IdempotencyKeyType),
});

export declare namespace PostProcessApiResponse {
    interface Raw {
        request: serializers.RequestType.Raw;
        idempotencyKey: serializers.IdempotencyKeyType.Raw;
    }
}
