/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const RequestPreProcessResponse: core.serialization.ObjectSchema<
    serializers.RequestPreProcessResponse.Raw,
    IntegralApi.RequestPreProcessResponse
> = core.serialization.object({
    hasResponseContent: core.serialization.boolean(),
    environment: core.serialization.string(),
    id: core.serialization.string(),
    endpoint: core.serialization.lazyObject(async () => (await import("../../..")).EndpointPreProcessType),
});

export declare namespace RequestPreProcessResponse {
    interface Raw {
        hasResponseContent: boolean;
        environment: string;
        id: string;
        endpoint: serializers.EndpointPreProcessType.Raw;
    }
}
