/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ReturnBackToUserResponse: core.serialization.ObjectSchema<
    serializers.ReturnBackToUserResponse.Raw,
    IntegralApi.ReturnBackToUserResponse
> = core.serialization.object({
    message: core.serialization.string(),
    solution: core.serialization.string(),
    apiKey: core.serialization.string().optional(),
    error: core.serialization.boolean().optional(),
    errorCode: core.serialization.string(),
    displayMessage: core.serialization.string(),
    documentationUrl: core.serialization.string().optional(),
    causes: core.serialization.string().optional(),
});

export declare namespace ReturnBackToUserResponse {
    interface Raw {
        message: string;
        solution: string;
        apiKey?: string | null;
        error?: boolean | null;
        errorCode: string;
        displayMessage: string;
        documentationUrl?: string | null;
        causes?: string | null;
    }
}
