/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const ReturnBackToUserUnionType: core.serialization.Schema<
    serializers.ReturnBackToUserUnionType.Raw,
    IntegralApi.ReturnBackToUserUnionType
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("../../..")).ReturnBackToUserErrorResponse),
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
]);

export declare namespace ReturnBackToUserUnionType {
    type Raw = serializers.ReturnBackToUserErrorResponse.Raw | Record<string, unknown>;
}
