/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../../core";

export const UserParseResponse: core.serialization.ObjectSchema<
    serializers.UserParseResponse.Raw,
    IntegralApi.UserParseResponse
> = core.serialization.object({
    integralId: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    userForeignId: core.serialization.string().optional(),
    isAllowlistedOnEndpoint: core.serialization.boolean().optional(),
    createdAt: core.serialization.string().optional(),
    updatedAt: core.serialization.string().optional(),
    deletedAt: core.serialization.string().optional(),
});

export declare namespace UserParseResponse {
    interface Raw {
        integralId?: string | null;
        metadata?: Record<string, unknown> | null;
        userForeignId?: string | null;
        isAllowlistedOnEndpoint?: boolean | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        deletedAt?: string | null;
    }
}
