/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetLogsByApplication {
    limit?: number;
    startingAfter?: string;
    /**
     * The user ID of the user you want the logs for on a given application, from your user table
     */
    userId?: string;
}
