/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { IntegralApi } from "@integralapi/node";
import * as core from "../../../core";

export type Response = core.APIResponse<IntegralApi.ApiKey, IntegralApi.apiKeys.revoke.Error>;
export type Error = IntegralApi.apiKeys.revoke.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: IntegralApi.apiKeys.revoke.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  _unknown: (fetcherError: core.Fetcher.Error): IntegralApi.apiKeys.revoke.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<IntegralApi.apiKeys.revoke.Error._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: IntegralApi.apiKeys.revoke.Error._Unknown, visitor: IntegralApi.apiKeys.revoke.Error._Visitor<_Result>) {
      return IntegralApi.apiKeys.revoke.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: IntegralApi.apiKeys.revoke.Error,
    visitor: IntegralApi.apiKeys.revoke.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      default:
        return visitor._other(value as any);
    }
  },
} as const;
