/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { IntegralApi } from "@integralapi/node";
import * as core from "../../../core";

export const ApplicationUser: core.schemas.ObjectSchema<serializers.ApplicationUser.Raw, IntegralApi.ApplicationUser> =
  core.schemas.object({
    id: core.schemas.string(),
    createdAt: core.schemas.string(),
    updatedAt: core.schemas.string(),
    deletedAt: core.schemas.string(),
    applicationUserForeignId: core.schemas.string(),
  });

export declare namespace ApplicationUser {
  interface Raw {
    id: string;
    createdAt: string;
    updatedAt: string;
    deletedAt: string;
    applicationUserForeignId: string;
  }
}
